# Generated by Django 2.1.5 on 2020-02-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshopa', '0002_auto_20200216_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='petshop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
